package com.lindungisesama.utils

enum class RichContentType {
	UNKNOWN, HEADING, HEADING1, HEADING2, HEADING3, HEADING4, HEADING5, HEADING6, PARAGRAPH, IMAGE,
	VIDEO, PREFORMATTED, LIST_ITEM, O_LIST_ITEM
}